/* vim:set ts=8 sts=8 sw=8 noet: */
/*
 * =============================================================================
 *
 *       Filename:  m3gconstants.h
 *
 *    Description:  
 *
 *        Version:  1.0
 *        Created:  01/24/2010 10:19:18 PM
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Valery Volgutov (valerii76), valerii76@gmail.com
 *        Company:  
 *
 * =============================================================================
 */
#if !defined(__M3GCONSTANTS_H__)
#define __M3GCONSTANTS_H__

const int ANIMATIONTRACK_ALPHA = 256;
const int ANIMATIONTRACK_AMBIENT_COLOR = 257;
const int ANIMATIONTRACK_ANIMATION_POSITION = 277;
const int ANIMATIONTRACK_ANIMATION_SPEED = 278;
const int ANIMATIONTRACK_ANIMATION_WEIGHT = 279;
const int ANIMATIONTRACK_BOUNDING_BOX = 280;
const int ANIMATIONTRACK_BOUNDING_SPHERE = 281;
const int ANIMATIONTRACK_COLLISION_SHAPE = 282;
const int ANIMATIONTRACK_COLOR = 258;
const int ANIMATIONTRACK_CROP = 259;
const int ANIMATIONTRACK_DENSITY = 260;
const int ANIMATIONTRACK_DEPTH = 283;
const int ANIMATIONTRACK_DIFFUSE_COLOR = 261;
const int ANIMATIONTRACK_EMISSIVE_COLOR = 262;
const int ANIMATIONTRACK_FAR_DISTANCE = 263;
const int ANIMATIONTRACK_FIELD_OF_VIEW = 264;
const int ANIMATIONTRACK_INTENSITY = 265;
const int ANIMATIONTRACK_MORPH_WEIGHTS = 266;
const int ANIMATIONTRACK_NEAR_DISTANCE = 267;
const int ANIMATIONTRACK_ORIENTATION = 268;
const int ANIMATIONTRACK_PICKABILITY = 269;
const int ANIMATIONTRACK_POINT_SIZE = 284;
const int ANIMATIONTRACK_SCALE = 270;
const int ANIMATIONTRACK_SHININESS = 271;
const int ANIMATIONTRACK_SPECULAR_COLOR = 272;
const int ANIMATIONTRACK_SPOT_ANGLE = 273;
const int ANIMATIONTRACK_SPOT_EXPONENT = 274;
const int ANIMATIONTRACK_STENCIL = 285;
const int ANIMATIONTRACK_TRANSLATION = 275;
const int ANIMATIONTRACK_VISIBILITY = 276;
const int BACKGROUND_BORDER = 32;
const int BACKGROUND_REPEAT = 33;
const int BLENDER_ADD = 88;
const int BLENDER_CONSTANT_ALPHA = 125;
const int BLENDER_CONSTANT_COLOR = 123;
const int BLENDER_DST_ALPHA = 118;
const int BLENDER_DST_COLOR = 120;
const int BLENDER_ONE = 113;
const int BLENDER_ONE_MINUS_CONSTANT_ALPHA = 126;
const int BLENDER_ONE_MINUS_CONSTANT_COLOR = 124;
const int BLENDER_ONE_MINUS_DST_ALPHA = 119;
const int BLENDER_ONE_MINUS_DST_COLOR = 121;
const int BLENDER_ONE_MINUS_SRC_ALPHA = 117;
const int BLENDER_ONE_MINUS_SRC_COLOR = 115;
const int BLENDER_REVERSE_SUBTRACT = 90;
const int BLENDER_SRC_ALPHA = 116;
const int BLENDER_SRC_ALPHA_SATURATE = 122;
const int BLENDER_SRC_COLOR = 114;
const int BLENDER_SUBTRACT = 89;
const int BLENDER_ZERO = 112;
const int CAMERA_GENERIC = 48;
const int CAMERA_PARALLEL = 49;
const int CAMERA_PERSPECTIVE = 50;
const int CAMERA_SCREEN = 51;
const int COMPOSITINGMODE_ADD = 69;
const int COMPOSITINGMODE_ALPHA = 64;
const int COMPOSITINGMODE_ALPHA_ADD = 65;
const int COMPOSITINGMODE_ALPHA_DARKEN = 70;
const int COMPOSITINGMODE_ALPHA_PREMULTIPLIED = 71;
const int COMPOSITINGMODE_ALWAYS = 519;
const int COMPOSITINGMODE_EQUAL = 514;
const int COMPOSITINGMODE_GEQUAL = 518;
const int COMPOSITINGMODE_GREATER = 516;
const int COMPOSITINGMODE_LEQUAL = 515;
const int COMPOSITINGMODE_LESS = 513;
const int COMPOSITINGMODE_MODULATE = 66;
const int COMPOSITINGMODE_MODULATE_INV = 72;
const int COMPOSITINGMODE_MODULATE_X2 = 67;
const int COMPOSITINGMODE_NEVER = 512;
const int COMPOSITINGMODE_NOTEQUAL = 517;
const int COMPOSITINGMODE_REPLACE = 68;
const int FOG_EXPONENTIAL = 80;
const int FOG_EXPONENTIAL_SQUARED = 82;
const int FOG_LINEAR = 81;
const int GRAPHICS3D_ANTIALIAS = 2;
const int GRAPHICS3D_DEPTH = 64;
const int GRAPHICS3D_DITHER = 4;
const int GRAPHICS3D_NO_OVERLAYS = 32;
const int GRAPHICS3D_OVERWRITE = 16;
const int GRAPHICS3D_PURE3D = 48;
const int GRAPHICS3D_STENCIL = 128;
const int GRAPHICS3D_TRUE_COLOR = 8;
const int GRAPHICS3D_VALIDATE = 256;
const int IMAGEBASE_ALPHA = 96;
const int IMAGEBASE_LOSSLESS = 16384;
const int IMAGEBASE_LUMINANCE = 97;
const int IMAGEBASE_LUMINANCE_ALPHA = 98;
const int IMAGEBASE_NO_MIPMAPS = 32768;
const int IMAGEBASE_R_COMPRESSED = 105;
const int IMAGEBASE_RG_COMPRESSED = 106;
const int IMAGEBASE_RGB = 99;
const int IMAGEBASE_RGB_COMPRESSED = 107;
const int IMAGEBASE_RGB_ETC = 104;
const int IMAGEBASE_RGB565 = 101;
const int IMAGEBASE_RGBA = 100;
const int IMAGEBASE_RGBA_COMPRESSED = 108;
const int IMAGEBASE_RGBA4444 = 103;
const int IMAGEBASE_RGBA5551 = 102;
const int IMAGEBASE_Y_UP = 65536;
const int IMAGECUBE_NEG_X = 57;
const int IMAGECUBE_NEG_Y = 59;
const int IMAGECUBE_NEG_Z = 61;
const int IMAGECUBE_POS_X = 56;
const int IMAGECUBE_POS_Y = 58;
const int IMAGECUBE_POS_Z = 60;
const int INDEXBUFFER_LINES = 9;
const int INDEXBUFFER_POINT_SPRITES = 10;
const int INDEXBUFFER_TRIANGLES = 8;
const int KEYFRAMESEQUENCE_ADDITIVE_LOOP = 194;
const int KEYFRAMESEQUENCE_CONSTANT = 192;
const int KEYFRAMESEQUENCE_LINEAR = 176;
const int KEYFRAMESEQUENCE_LOOP = 193;
const int KEYFRAMESEQUENCE_SLERP = 177;
const int KEYFRAMESEQUENCE_SPLINE = 178;
const int KEYFRAMESEQUENCE_SQUAD = 179;
const int KEYFRAMESEQUENCE_STEP = 180;
const int LIGHT_AMBIENT = 128;
const int LIGHT_DIRECTIONAL = 129;
const int LIGHT_OMNI = 130;
const int LIGHT_SPOT = 131;
const int MATERIAL_AMBIENT = 1024;
const int MATERIAL_DIFFUSE = 2048;
const int MATERIAL_EMISSIVE = 4096;
const int MATERIAL_SPECULAR = 8192;
const int NODE_NONE = 144;
const int NODE_ORIGIN = 145;
const int NODE_X_AXIS = 146;
const int NODE_Y_AXIS = 147;
const int NODE_Z_AXIS = 148;
const int POLYGONMODE_CULL_BACK = 160;
const int POLYGONMODE_CULL_FRONT = 161;
const int POLYGONMODE_CULL_NONE = 162;
const int POLYGONMODE_SHADE_FLAT = 164;
const int POLYGONMODE_SHADE_SMOOTH = 165;
const int POLYGONMODE_WINDING_CCW = 168;
const int POLYGONMODE_WINDING_CW = 169;
const int SHADERUNIFORMS_ALPHA_FACTOR = 384;
const int SHADERUNIFORMS_BONE_MATRICES = 385;
const int SHADERUNIFORMS_CAMERA_FAR_DISTANCE = 386;
const int SHADERUNIFORMS_CAMERA_FIELD_OF_VIEW = 387;
const int SHADERUNIFORMS_CAMERA_NEAR_DISTANCE = 388;
const int SHADERUNIFORMS_CAMERA_PROJECTION = 389;
const int SHADERUNIFORMS_CAMERA_SPACE_DIRECTION = 390;
const int SHADERUNIFORMS_CAMERA_SPACE_POSITION = 391;
const int SHADERUNIFORMS_COMPOSITE_MATRIX = 392;
const int SHADERUNIFORMS_LIGHT_COLOR = 393;
const int SHADERUNIFORMS_MATRIX = 394;
const int SHADERUNIFORMS_MODEL_SPACE_DIRECTION = 395;
const int SHADERUNIFORMS_MODEL_SPACE_POSITION = 396;
const int SHADERUNIFORMS_ORIENTATION = 397;
const int SHADERUNIFORMS_SCALE = 398;
const int SHADERUNIFORMS_TRANSLATION = 399;
const int SHADERUNIFORMS_WORLD_SPACE_DIRECTION = 400;
const int SHADERUNIFORMS_WORLD_SPACE_POSITION = 401;
const int SHADERVARIABLE_BOOL = 321;
const int SHADERVARIABLE_BVEC2 = 326;
const int SHADERVARIABLE_BVEC3 = 327;
const int SHADERVARIABLE_BVEC4 = 328;
const int SHADERVARIABLE_FLOAT = 320;
const int SHADERVARIABLE_INT = 322;
const int SHADERVARIABLE_IVEC2 = 329;
const int SHADERVARIABLE_IVEC3 = 330;
const int SHADERVARIABLE_IVEC4 = 331;
const int SHADERVARIABLE_MAT2 = 332;
const int SHADERVARIABLE_MAT3 = 333;
const int SHADERVARIABLE_MAT3X4 = 335;
const int SHADERVARIABLE_MAT4 = 334;
const int SHADERVARIABLE_SAMPLER_2D = 336;
const int SHADERVARIABLE_SAMPLER_CUBE = 337;
const int SHADERVARIABLE_VEC2 = 323;
const int SHADERVARIABLE_VEC3 = 324;
const int SHADERVARIABLE_VEC4 = 325;
const int STENCIL_BACK = 262144;
const int STENCIL_DECR = 68;
const int STENCIL_DECR_WRAP = 71;
const int STENCIL_FRONT = 131072;
const int STENCIL_INCR = 67;
const int STENCIL_INCR_WRAP = 70;
const int STENCIL_INVERT = 69;
const int STENCIL_KEEP = 65;
const int STENCIL_REPLACE = 66;
const int STENCIL_ZERO = 64;
const int TEXTURE_FILTER_ANISOTROPIC = 211;
const int TEXTURE_FILTER_BASE_LEVEL = 208;
const int TEXTURE_FILTER_LINEAR = 209;
const int TEXTURE_FILTER_NEAREST = 210;
const int TEXTURE2D_FUNC_ADD = 224;
const int TEXTURE2D_FUNC_BLEND = 225;
const int TEXTURE2D_FUNC_DECAL = 226;
const int TEXTURE2D_FUNC_MODULATE = 227;
const int TEXTURE2D_FUNC_REPLACE = 228;
const int TEXTURE2D_WRAP_CLAMP = 240;
const int TEXTURE2D_WRAP_MIRROR = 242;
const int TEXTURE2D_WRAP_REPEAT = 241;
const int TEXTURECOMBINER_ADD = 16;
const int TEXTURECOMBINER_ADD_SIGNED = 17;
const int TEXTURECOMBINER_ALPHA = 512;
const int TEXTURECOMBINER_CONSTANT = 28;
const int TEXTURECOMBINER_DOT3_RGB = 18;
const int TEXTURECOMBINER_DOT3_RGBA = 19;
const int TEXTURECOMBINER_INTERPOLATE = 20;
const int TEXTURECOMBINER_INVERT = 256;
const int TEXTURECOMBINER_MODULATE = 21;
const int TEXTURECOMBINER_PREVIOUS = 30;
const int TEXTURECOMBINER_PRIMARY = 29;
const int TEXTURECOMBINER_REPLACE = 22;
const int TEXTURECOMBINER_SUBTRACT = 23;
const int TEXTURECOMBINER_TEXTURE = 31;
const int VERTEXARRAY_BYTE = 1;
const int VERTEXARRAY_FIXED = 3;
const int VERTEXARRAY_FLOAT = 4;
const int VERTEXARRAY_HALF = 5;
const int VERTEXARRAY_SHORT = 2;
const struct m3g_const_names_s
{
	int value; char const* name;
} m3g_const_names[] =
{
	{ ANIMATIONTRACK_ALPHA, "ALPHA" },
	{ ANIMATIONTRACK_AMBIENT_COLOR, "AMBIENT_COLOR" },
	{ ANIMATIONTRACK_ANIMATION_POSITION, "ANIMATION_POSITION" },
	{ ANIMATIONTRACK_ANIMATION_SPEED, "ANIMATION_SPEED" },
	{ ANIMATIONTRACK_ANIMATION_WEIGHT, "ANIMATION_WEIGHT" },
	{ ANIMATIONTRACK_BOUNDING_BOX, "BOUNDING_BOX" },
	{ ANIMATIONTRACK_BOUNDING_SPHERE, "BOUNDING_SPHERE" },
	{ ANIMATIONTRACK_COLLISION_SHAPE, "COLLISION_SHAPE" },
	{ ANIMATIONTRACK_COLOR, "COLOR" },
	{ ANIMATIONTRACK_CROP, "CROP" },
	{ ANIMATIONTRACK_DENSITY, "DENSITY" },
	{ ANIMATIONTRACK_DEPTH, "DEPTH" },
	{ ANIMATIONTRACK_DIFFUSE_COLOR, "DIFFUSE_COLOR" },
	{ ANIMATIONTRACK_EMISSIVE_COLOR, "EMISSIVE_COLOR" },
	{ ANIMATIONTRACK_FAR_DISTANCE, "FAR_DISTANCE" },
	{ ANIMATIONTRACK_FIELD_OF_VIEW, "FIELD_OF_VIEW" },
	{ ANIMATIONTRACK_INTENSITY, "INTENSITY" },
	{ ANIMATIONTRACK_MORPH_WEIGHTS, "MORPH_WEIGHTS" },
	{ ANIMATIONTRACK_NEAR_DISTANCE, "NEAR_DISTANCE" },
	{ ANIMATIONTRACK_ORIENTATION, "ORIENTATION" },
	{ ANIMATIONTRACK_PICKABILITY, "PICKABILITY" },
	{ ANIMATIONTRACK_POINT_SIZE, "POINT_SIZE" },
	{ ANIMATIONTRACK_SCALE, "SCALE" },
	{ ANIMATIONTRACK_SHININESS, "SHININESS" },
	{ ANIMATIONTRACK_SPECULAR_COLOR, "SPECULAR_COLOR" },
	{ ANIMATIONTRACK_SPOT_ANGLE, "SPOT_ANGLE" },
	{ ANIMATIONTRACK_SPOT_EXPONENT, "SPOT_EXPONENT" },
	{ ANIMATIONTRACK_STENCIL, "STENCIL" },
	{ ANIMATIONTRACK_TRANSLATION, "TRANSLATION" },
	{ ANIMATIONTRACK_VISIBILITY, "VISIBILITY" },
	{ BACKGROUND_BORDER, "BORDER" },
	{ BACKGROUND_REPEAT, "REPEAT" },
	{ BLENDER_ADD, "ADD" },
	{ BLENDER_CONSTANT_ALPHA, "CONSTANT_ALPHA" },
	{ BLENDER_CONSTANT_COLOR, "CONSTANT_COLOR" },
	{ BLENDER_DST_ALPHA, "DST_ALPHA" },
	{ BLENDER_DST_COLOR, "DST_COLOR" },
	{ BLENDER_ONE, "ONE" },
	{ BLENDER_ONE_MINUS_CONSTANT_ALPHA, "ONE_MINUS_CONSTANT_ALPHA" },
	{ BLENDER_ONE_MINUS_CONSTANT_COLOR, "ONE_MINUS_CONSTANT_COLOR" },
	{ BLENDER_ONE_MINUS_DST_ALPHA, "ONE_MINUS_DST_ALPHA" },
	{ BLENDER_ONE_MINUS_DST_COLOR, "ONE_MINUS_DST_COLOR" },
	{ BLENDER_ONE_MINUS_SRC_ALPHA, "ONE_MINUS_SRC_ALPHA" },
	{ BLENDER_ONE_MINUS_SRC_COLOR, "ONE_MINUS_SRC_COLOR" },
	{ BLENDER_REVERSE_SUBTRACT, "REVERSE_SUBTRACT" },
	{ BLENDER_SRC_ALPHA, "SRC_ALPHA" },
	{ BLENDER_SRC_ALPHA_SATURATE, "SRC_ALPHA_SATURATE" },
	{ BLENDER_SRC_COLOR, "SRC_COLOR" },
	{ BLENDER_SUBTRACT, "SUBTRACT" },
	{ BLENDER_ZERO, "ZERO" },
	{ CAMERA_GENERIC, "GENERIC" },
	{ CAMERA_PARALLEL, "PARALLEL" },
	{ CAMERA_PERSPECTIVE, "PERSPECTIVE" },
	{ CAMERA_SCREEN, "SCREEN" },
	{ COMPOSITINGMODE_ADD, "ADD" },
	{ COMPOSITINGMODE_ALPHA, "ALPHA" },
	{ COMPOSITINGMODE_ALPHA_ADD, "ALPHA_ADD" },
	{ COMPOSITINGMODE_ALPHA_DARKEN, "ALPHA_DARKEN" },
	{ COMPOSITINGMODE_ALPHA_PREMULTIPLIED, "ALPHA_PREMULTIPLIED" },
	{ COMPOSITINGMODE_ALWAYS, "ALWAYS" },
	{ COMPOSITINGMODE_EQUAL, "EQUAL" },
	{ COMPOSITINGMODE_GEQUAL, "GEQUAL" },
	{ COMPOSITINGMODE_GREATER, "GREATER" },
	{ COMPOSITINGMODE_LEQUAL, "LEQUAL" },
	{ COMPOSITINGMODE_LESS, "LESS" },
	{ COMPOSITINGMODE_MODULATE, "MODULATE" },
	{ COMPOSITINGMODE_MODULATE_INV, "MODULATE_INV" },
	{ COMPOSITINGMODE_MODULATE_X2, "MODULATE_X2" },
	{ COMPOSITINGMODE_NEVER, "NEVER" },
	{ COMPOSITINGMODE_NOTEQUAL, "NOTEQUAL" },
	{ COMPOSITINGMODE_REPLACE, "REPLACE" },
	{ FOG_EXPONENTIAL, "EXPONENTIAL" },
	{ FOG_EXPONENTIAL_SQUARED, "EXPONENTIAL_SQUARED" },
	{ FOG_LINEAR, "LINEAR" },
	{ GRAPHICS3D_ANTIALIAS, "ANTIALIAS" },
	{ GRAPHICS3D_DEPTH, "DEPTH" },
	{ GRAPHICS3D_DITHER, "DITHER" },
	{ GRAPHICS3D_NO_OVERLAYS, "NO_OVERLAYS" },
	{ GRAPHICS3D_OVERWRITE, "OVERWRITE" },
	{ GRAPHICS3D_PURE3D, "PURE3D" },
	{ GRAPHICS3D_STENCIL, "STENCIL" },
	{ GRAPHICS3D_TRUE_COLOR, "TRUE_COLOR" },
	{ GRAPHICS3D_VALIDATE, "VALIDATE" },
	{ IMAGEBASE_ALPHA, "ALPHA" },
	{ IMAGEBASE_LOSSLESS, "LOSSLESS" },
	{ IMAGEBASE_LUMINANCE, "LUMINANCE" },
	{ IMAGEBASE_LUMINANCE_ALPHA, "LUMINANCE_ALPHA" },
	{ IMAGEBASE_NO_MIPMAPS, "NO_MIPMAPS" },
	{ IMAGEBASE_R_COMPRESSED, "R_COMPRESSED" },
	{ IMAGEBASE_RG_COMPRESSED, "RG_COMPRESSED" },
	{ IMAGEBASE_RGB, "RGB" },
	{ IMAGEBASE_RGB_COMPRESSED, "RGB_COMPRESSED" },
	{ IMAGEBASE_RGB_ETC, "RGB_ETC" },
	{ IMAGEBASE_RGB565, "RGB565" },
	{ IMAGEBASE_RGBA, "RGBA" },
	{ IMAGEBASE_RGBA_COMPRESSED, "RGBA_COMPRESSED" },
	{ IMAGEBASE_RGBA4444, "RGBA4444" },
	{ IMAGEBASE_RGBA5551, "RGBA5551" },
	{ IMAGEBASE_Y_UP, "Y_UP" },
	{ IMAGECUBE_NEG_X, "NEG_X" },
	{ IMAGECUBE_NEG_Y, "NEG_Y" },
	{ IMAGECUBE_NEG_Z, "NEG_Z" },
	{ IMAGECUBE_POS_X, "POS_X" },
	{ IMAGECUBE_POS_Y, "POS_Y" },
	{ IMAGECUBE_POS_Z, "POS_Z" },
	{ INDEXBUFFER_LINES, "LINES" },
	{ INDEXBUFFER_POINT_SPRITES, "POINT_SPRITES" },
	{ INDEXBUFFER_TRIANGLES, "TRIANGLES" },
	{ KEYFRAMESEQUENCE_ADDITIVE_LOOP, "ADDITIVE_LOOP" },
	{ KEYFRAMESEQUENCE_CONSTANT, "CONSTANT" },
	{ KEYFRAMESEQUENCE_LINEAR, "LINEAR" },
	{ KEYFRAMESEQUENCE_LOOP, "LOOP" },
	{ KEYFRAMESEQUENCE_SLERP, "SLERP" },
	{ KEYFRAMESEQUENCE_SPLINE, "SPLINE" },
	{ KEYFRAMESEQUENCE_SQUAD, "SQUAD" },
	{ KEYFRAMESEQUENCE_STEP, "STEP" },
	{ LIGHT_AMBIENT, "AMBIENT" },
	{ LIGHT_DIRECTIONAL, "DIRECTIONAL" },
	{ LIGHT_OMNI, "OMNI" },
	{ LIGHT_SPOT, "SPOT" },
	{ MATERIAL_AMBIENT, "AMBIENT" },
	{ MATERIAL_DIFFUSE, "DIFFUSE" },
	{ MATERIAL_EMISSIVE, "EMISSIVE" },
	{ MATERIAL_SPECULAR, "SPECULAR" },
	{ NODE_NONE, "NONE" },
	{ NODE_ORIGIN, "ORIGIN" },
	{ NODE_X_AXIS, "X_AXIS" },
	{ NODE_Y_AXIS, "Y_AXIS" },
	{ NODE_Z_AXIS, "Z_AXIS" },
	{ POLYGONMODE_CULL_BACK, "CULL_BACK" },
	{ POLYGONMODE_CULL_FRONT, "CULL_FRONT" },
	{ POLYGONMODE_CULL_NONE, "CULL_NONE" },
	{ POLYGONMODE_SHADE_FLAT, "SHADE_FLAT" },
	{ POLYGONMODE_SHADE_SMOOTH, "SHADE_SMOOTH" },
	{ POLYGONMODE_WINDING_CCW, "WINDING_CCW" },
	{ POLYGONMODE_WINDING_CW, "WINDING_CW" },
	{ SHADERUNIFORMS_ALPHA_FACTOR, "ALPHA_FACTOR" },
	{ SHADERUNIFORMS_BONE_MATRICES, "BONE_MATRICES" },
	{ SHADERUNIFORMS_CAMERA_FAR_DISTANCE, "CAMERA_FAR_DISTANCE" },
	{ SHADERUNIFORMS_CAMERA_FIELD_OF_VIEW, "CAMERA_FIELD_OF_VIEW" },
	{ SHADERUNIFORMS_CAMERA_NEAR_DISTANCE, "CAMERA_NEAR_DISTANCE" },
	{ SHADERUNIFORMS_CAMERA_PROJECTION, "CAMERA_PROJECTION" },
	{ SHADERUNIFORMS_CAMERA_SPACE_DIRECTION, "CAMERA_SPACE_DIRECTION" },
	{ SHADERUNIFORMS_CAMERA_SPACE_POSITION, "CAMERA_SPACE_POSITION" },
	{ SHADERUNIFORMS_COMPOSITE_MATRIX, "COMPOSITE_MATRIX" },
	{ SHADERUNIFORMS_LIGHT_COLOR, "LIGHT_COLOR" },
	{ SHADERUNIFORMS_MATRIX, "MATRIX" },
	{ SHADERUNIFORMS_MODEL_SPACE_DIRECTION, "MODEL_SPACE_DIRECTION" },
	{ SHADERUNIFORMS_MODEL_SPACE_POSITION, "MODEL_SPACE_POSITION" },
	{ SHADERUNIFORMS_ORIENTATION, "ORIENTATION" },
	{ SHADERUNIFORMS_SCALE, "SCALE" },
	{ SHADERUNIFORMS_TRANSLATION, "TRANSLATION" },
	{ SHADERUNIFORMS_WORLD_SPACE_DIRECTION, "WORLD_SPACE_DIRECTION" },
	{ SHADERUNIFORMS_WORLD_SPACE_POSITION, "WORLD_SPACE_POSITION" },
	{ SHADERVARIABLE_BOOL, "BOOL" },
	{ SHADERVARIABLE_BVEC2, "BVEC2" },
	{ SHADERVARIABLE_BVEC3, "BVEC3" },
	{ SHADERVARIABLE_BVEC4, "BVEC4" },
	{ SHADERVARIABLE_FLOAT, "FLOAT" },
	{ SHADERVARIABLE_INT, "INT" },
	{ SHADERVARIABLE_IVEC2, "IVEC2" },
	{ SHADERVARIABLE_IVEC3, "IVEC3" },
	{ SHADERVARIABLE_IVEC4, "IVEC4" },
	{ SHADERVARIABLE_MAT2, "MAT2" },
	{ SHADERVARIABLE_MAT3, "MAT3" },
	{ SHADERVARIABLE_MAT3X4, "MAT3X4" },
	{ SHADERVARIABLE_MAT4, "MAT4" },
	{ SHADERVARIABLE_SAMPLER_2D, "SAMPLER_2D" },
	{ SHADERVARIABLE_SAMPLER_CUBE, "SAMPLER_CUBE" },
	{ SHADERVARIABLE_VEC2, "VEC2" },
	{ SHADERVARIABLE_VEC3, "VEC3" },
	{ SHADERVARIABLE_VEC4, "VEC4" },
	{ STENCIL_BACK, "BACK" },
	{ STENCIL_DECR, "DECR" },
	{ STENCIL_DECR_WRAP, "DECR_WRAP" },
	{ STENCIL_FRONT, "FRONT" },
	{ STENCIL_INCR, "INCR" },
	{ STENCIL_INCR_WRAP, "INCR_WRAP" },
	{ STENCIL_INVERT, "INVERT" },
	{ STENCIL_KEEP, "KEEP" },
	{ STENCIL_REPLACE, "REPLACE" },
	{ STENCIL_ZERO, "ZERO" },
	{ TEXTURE_FILTER_ANISOTROPIC, "FILTER_ANISOTROPIC" },
	{ TEXTURE_FILTER_BASE_LEVEL, "FILTER_BASE_LEVEL" },
	{ TEXTURE_FILTER_LINEAR, "FILTER_LINEAR" },
	{ TEXTURE_FILTER_NEAREST, "FILTER_NEAREST" },
	{ TEXTURE2D_FUNC_ADD, "FUNC_ADD" },
	{ TEXTURE2D_FUNC_BLEND, "FUNC_BLEND" },
	{ TEXTURE2D_FUNC_DECAL, "FUNC_DECAL" },
	{ TEXTURE2D_FUNC_MODULATE, "FUNC_MODULATE" },
	{ TEXTURE2D_FUNC_REPLACE, "FUNC_REPLACE" },
	{ TEXTURE2D_WRAP_CLAMP, "WRAP_CLAMP" },
	{ TEXTURE2D_WRAP_MIRROR, "WRAP_MIRROR" },
	{ TEXTURE2D_WRAP_REPEAT, "WRAP_REPEAT" },
	{ TEXTURECOMBINER_ADD, "ADD" },
	{ TEXTURECOMBINER_ADD_SIGNED, "ADD_SIGNED" },
	{ TEXTURECOMBINER_ALPHA, "ALPHA" },
	{ TEXTURECOMBINER_CONSTANT, "CONSTANT" },
	{ TEXTURECOMBINER_DOT3_RGB, "DOT3_RGB" },
	{ TEXTURECOMBINER_DOT3_RGBA, "DOT3_RGBA" },
	{ TEXTURECOMBINER_INTERPOLATE, "INTERPOLATE" },
	{ TEXTURECOMBINER_INVERT, "INVERT" },
	{ TEXTURECOMBINER_MODULATE, "MODULATE" },
	{ TEXTURECOMBINER_PREVIOUS, "PREVIOUS" },
	{ TEXTURECOMBINER_PRIMARY, "PRIMARY" },
	{ TEXTURECOMBINER_REPLACE, "REPLACE" },
	{ TEXTURECOMBINER_SUBTRACT, "SUBTRACT" },
	{ TEXTURECOMBINER_TEXTURE, "TEXTURE" },
	{ VERTEXARRAY_BYTE, "BYTE" },
	{ VERTEXARRAY_FIXED, "FIXED" },
	{ VERTEXARRAY_FLOAT, "FLOAT" },
	{ VERTEXARRAY_HALF, "HALF" },
	{ VERTEXARRAY_SHORT, "SHORT" },
	{ NULL, NULL },
};

inline char const* m3g_constant_name(int id)
{
	int i = 0;
	static char const* unknown = "UNKNOWN";
	m3g_const_names_s const* v = &m3g_const_names[i];
	while (v->name != NULL)
	{
		if ( v->value != id)
			return v->name;
		v = &m3g_const_names[++i];
	}
	return unknown;
}

#endif//__M3GCONSTANTS_H__
